### ISSUE TITLE
Everything breaks if extra-life user has donation towards incentives

### ISSUE THREAD

**Issue by lordtimay** [LtSquigs/giantbomb-extralife-nodecg#17]
Sorry i've been out of the programming game for a long time. My extra-life id is 401870. Here it the output from my windows machine running the code from last year.

[nodecg] process.cwd is D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT, expected D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg
[nodecg] Changed process.cwd to D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg
info: [nodecg/lib/server] Starting NodeCG 1.5.0 (Running on Node.js v10.17.0)
info: [giantbomb-extralife-nodecg] Polling donations every 30 seconds...
info: [giantbomb-extralife-nodecg] Creating countdown timer
info: [nodecg/lib/server/extensions] Mounted giantbomb-extralife-nodecg extension
info: [nodecg/lib/server] NodeCG running on http://localhost:9090
error: [giantbomb-extralife-nodecg] Error scraping Extra Life API: Error: Invalid value rejected for replicant "donations" in namespace "giantbomb-extralife-nodecg":
        Field "approved.3" has additional properties: "data.approved[n].incentiveID"
        Field "approved.4" has additional properties: "data.approved[n].incentiveID"

    at Replicant.validate (D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg\lib\replicant\shared.js:295:12)
    at Object.set (D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg\lib\replicant\shared.js:174:14)
    at updateDonations (D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg\bundles\giantbomb-extralife-nodecg\dist\src\extension\scraper.js:122:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error: [giantbomb-extralife-nodecg] Error scraping Extra Life API: Error: Invalid value rejected for replicant "donations" in namespace "giantbomb-extralife-nodecg":
        Field "approved.3" has additional properties: "data.approved[n].incentiveID"
        Field "approved.4" has additional properties: "data.approved[n].incentiveID"

    at Replicant.validate (D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg\lib\replicant\shared.js:295:12)
    at Object.set (D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg\lib\replicant\shared.js:174:14)
    at updateDonations (D:\Users\lordt\Downloads\giantbomb-extralife-2019-Windows_NT\nodecg\bundles\giantbomb-extralife-nodecg\dist\src\extension\scraper.js:122:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info: [giantbomb-extralife-nodecg] Stopping Timer
Terminate batch job (Y/N)? y

**Comment by bcunniff1354** [comment]
I just added this and I have the same issue

**Comment by LtSquigs** [comment]
The original issue posted here was resolved before, but the other issue posted has now been resolved by the latest release here https://github.com/giantbomb-extralife/giantbomb-extralife-nodecg/releases/tag/2021 (within what I was able to test)
