### ISSUE TITLE
Invalid JSON response (2022)

### ISSUE THREAD

**Issue by jasonsckrabulis** [LtSquigs/giantbomb-extralife-nodecg#28]
I'm setting up the overlay for my streams this year (2022) and ran into this error in the NodeCG terminal. Not sure what's changed (if anything) in the API, but that exact JSON call works in-browser. Thanks!

```
error: [giantbomb-extralife-nodecg] Error scraping Extra Life API: { FetchError: invalid json response body at https://www.extra-life.org/api/participants/477732/donations reason: Unexpected token T in JSON at position 0
    at D:\STREAMING\giantbomb-extralife-2021-Windows_NT\nodecg\bundles\giantbomb-extralife-nodecg\node_modules\node-fetch\lib\index.js:273:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://www.extra-life.org/api/participants/477732/donations reason: Unexpected token T in JSON at position 0',
  type: 'invalid-json' }
```

**Comment by jasonsckrabulis** [comment]
General notice was sent today that the API was having issues and not reflected on status.donordrive.com. Closed!
